version: '3'
services:

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress
    command: npm run cy:ci
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json
    privileged: true
    ipc: host
    shm_size: 1024M
