name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the stack
        run: docker-compose up
      - uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: /app/cypress/screenshots
