name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the stack
        run: docker-compose up

      - name: Copy screenshots
        run: |
          mkdir public
          cp -r cypress/screenshots public/screenshots

      - name: Combine reports
        run: npm run combine-reports

      - name: Generate reports
        run: npm run generate-report
