name: CypressCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the stack and test
        run: docker-compose up
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: cypress/screenshots